version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_PATH=/app/data/hackathon.db
    volumes:
      # Persist SQLite database - mount the entire data directory
      - hackathon-data:/app/data
    restart: unless-stopped

volumes:
  # Named volume for database persistence
  hackathon-data:
    driver: local
